# Generated by Django 5.1 on 2024-08-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('need_for_speed_app', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='number_of_workers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
