# Generated by Django 5.1 on 2024-08-26 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('need_for_speed_app', '0010_rename_read_notification_is_read_notification_action_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at']},
        ),
    ]
