# Generated by Django 5.1 on 2024-08-26 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('need_for_speed_app', '0012_remove_notification_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action',
            field=models.CharField(default='created', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.CharField(default='Post', max_length=100),
        ),
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(default='/', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='need_for_speed_app.user'),
        ),
    ]
